---
- name: Create document root
  ansible.builtin.file:
    path: "{{ wp_mw_role_vhost_webroot }}"
    state: directory
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: '0755'

- name: Create conf.d/ directory
  ansible.builtin.file:
    path: "{{ wp_mw_role_apache_conf_dir }}/conf.d"
    state: directory
    mode: '0755'
  tags: [apache]

- name: Ensure conf.d/*.conf is included in apache main config
  ansible.builtin.lineinfile:
    path: "{{ wp_mw_role_apache_main_conf_file }}"
    insertafter: EOF
    line: "IncludeOptional {{ wp_mw_role_apache_conf_dir }}/conf.d/*.conf"
    state: present
  notify: Reload Apache


- name: Set up Apache vhost config
  ansible.builtin.template:
    src: "apache.conf.j2"
    dest: "{{ apache_conf_dir }}/conf.d/{{ wp_mw_role_vhost_conf_name }}.conf"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: '0755'
  notify: Reload Apache

- name: Remove default site
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ apache_conf_dir }}/sites-enabled/000-default.conf"
    - "{{ apache_conf_dir }}/conf.d/welcome.conf"
  notify: Restart Apache
