---
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true

- name: Install Apache packages with APT
  ansible.builtin.apt:
    name: "{{ wp_mw_role_apache_packages }}"
    state: present

- name: Install LAMP packages with APT
  ansible.builtin.apt:
    name: "{{ wp_mw_role_lamp_packages }}"
    state: present

- name: Install PHP modules with APT
  ansible.builtin.apt:
    name: "{{ wp_mw_role_php_modules }}"
    state: present
